### INIT call
GET {{URL}}/api/init
Accept: application/json


### START call
POST {{URL}}/api/start
Content-Type: application/json
Accept: application/json

{
  "challenge": "K10CCY5I3158",
  "naam": "Jan de mooie"
}


### STOP call
POST {{URL}}/api/stop
Content-Type: application/json
Accept: application/json

{
  "challenge": "K10CCY5I3158",
  "score": 4
}

### TOP call
GET {{URL}}/api/top
Accept: application/json