### INIT call
GET {{URL}}/api/init
Accept: application/json


### START call
POST {{URL}}/api/start
Content-Type: application/json
Accept: application/json

{
  "challenge": "RQPRBMNX3158",
  "naam": "Jan de Nederlander"
}


### STOP call
POST {{URL}}/api/stop
Content-Type: application/json
Accept: application/json

{
  "challenge": "RQPRBMNX3158",
  "score": 7
}
